service: bird-detect-message-handler

custom:
  stage: ${opt:stage, 'dev'}
  iot:
    topicFilter: ${ssm:bird-detection-topic-filter}
  alexa:
    clientId: ${ssm:bird-detection-client-id}
    clientSecret: ${ssm:bird-detection-client-secret}
    notificationExpiryMinutes: 10

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.handler
    events:
      - iot:
          name: 'birdDetection'
          sql: "select bird from '${self:custom.iot.topicFilter}' where bird > 0.800"
    environment:
      STAGE: ${self:custom.stage}
      CLIENT_ID: ${self:custom.alexa.clientId}
      CLIENT_SECRET: ${self:custom.alexa.clientSecret}
      PROACTIVE_AUTH_ENDPOINT: https://api.amazon.com
      PROACTIVE_EVENT_ENDPOINT: https://api.amazonalexa.com
      ALEXA_NOTIFICATION_EXPIRY_MINUTES: ${self:custom.alexa.notificationExpiryMinutes}

